
# cargo-vet config file

[policy.linregress]
audit-as-crates-io = false

[[exemptions.approx]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.atty]]
version = "0.2.14"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-run"

[[exemptions.bstr]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.11.1"
criteria = "safe-to-run"

[[exemptions.bytemuck]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "2.34.0"
criteria = "safe-to-run"

[[exemptions.criterion]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.4.5"
criteria = "safe-to-run"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.11"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.12"
criteria = "safe-to-run"

[[exemptions.csv]]
version = "1.1.6"
criteria = "safe-to-run"

[[exemptions.csv-core]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.half]]
version = "1.8.2"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "0.4.8"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.60"
criteria = "safe-to-run"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.137"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.17"
criteria = "safe-to-run"

[[exemptions.matrixmultiply]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-run"

[[exemptions.nalgebra]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.nalgebra-macros]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.num-complex]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.num-rational]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.14.0"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.16.0"
criteria = "safe-to-run"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.paste]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.37"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.rawpointer]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.5.3"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.9.3"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.6.0"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.27"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-run"

[[exemptions.safe_arch]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.147"
criteria = "safe-to-run"

[[exemptions.serde_cbor]]
version = "0.11.2"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.147"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.87"
criteria = "safe-to-run"

[[exemptions.simba]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.92"
criteria = "safe-to-deploy"

[[exemptions.textwrap]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.3.2"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.60"
criteria = "safe-to-run"

[[exemptions.wide]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

